"""
SyntheaIngestionAgent — loads FHIR R4 bundle JSON files generated by Synthea
from disk and populates the HealthIQ database.

Key difference from IngestionAgent (live HAPI REST API):
  - Reads local .json files instead of HTTP requests
  - Handles urn:uuid: intra-bundle references (Synthea uses these instead of
    Patient/<id> style references)
  - Processes Condition + MedicationRequest in addition to the base 3 types

urn:uuid reference resolution:
  Synthea bundle entries have fullUrl = "urn:uuid:<resource-id>".
  Cross-resource references look like: "subject": {"reference": "urn:uuid:<id>"}
  The existing mappers split on "/" and take the last segment, so
  "urn:uuid:abc".split("/") = ["urn:uuid:abc"] — last is "urn:uuid:abc".
  We therefore key patient_fhir_to_db with BOTH the bare id AND "urn:uuid:<id>"
  so lookups succeed regardless of which reference format a resource uses.
"""

import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from sqlalchemy.orm import Session

from agents.ingestion.mapper import (
    map_condition,
    map_encounter,
    map_medication_request,
    map_observation,
    map_patient,
)
from api.models.condition import Condition
from api.models.encounter import Encounter
from api.models.medication_request import MedicationRequest
from api.models.observation import Observation
from api.models.patient import Patient

logger = logging.getLogger(__name__)


@dataclass
class ResourceSummary:
    fetched: int = 0
    inserted: int = 0
    skipped: int = 0
    errors: int = 0


@dataclass
class SyntheaIngestionSummary:
    bundle_files: int = 0
    patients: ResourceSummary = field(default_factory=ResourceSummary)
    encounters: ResourceSummary = field(default_factory=ResourceSummary)
    observations: ResourceSummary = field(default_factory=ResourceSummary)
    conditions: ResourceSummary = field(default_factory=ResourceSummary)
    medications: ResourceSummary = field(default_factory=ResourceSummary)
    duration_seconds: float = 0.0
    error_log: list[str] = field(default_factory=list)


class SyntheaIngestionAgent:
    # Synthea generates these non-patient bundle files; skip them
    _SKIP_PREFIXES = ("hospitalInformation", "practitionerInformation")

    def __init__(self, db: Session, bundle_dir: str) -> None:
        self._db = db
        self._bundle_dir = Path(bundle_dir)

    def run(self) -> SyntheaIngestionSummary:
        summary = SyntheaIngestionSummary()
        t0 = time.monotonic()

        bundle_files = self._find_bundles()
        summary.bundle_files = len(bundle_files)
        logger.info("Found %d Synthea bundle files in %s", len(bundle_files), self._bundle_dir)

        for i, path in enumerate(bundle_files, 1):
            if i % 50 == 0 or i == 1:
                logger.info("Processing bundle %d/%d", i, len(bundle_files))
            try:
                bundle = json.loads(path.read_text(encoding="utf-8"))
                self._process_bundle(bundle, summary)
            except Exception as exc:
                summary.error_log.append(f"Bundle {path.name}: {exc}")
                logger.exception("Failed to process bundle %s", path.name)

        summary.duration_seconds = round(time.monotonic() - t0, 2)
        logger.info(
            "Synthea ingestion complete in %.1fs — patients: %d inserted / %d skipped, "
            "encounters: %d, observations: %d, conditions: %d, medications: %d",
            summary.duration_seconds,
            summary.patients.inserted,
            summary.patients.skipped,
            summary.encounters.inserted,
            summary.observations.inserted,
            summary.conditions.inserted,
            summary.medications.inserted,
        )
        return summary

    # ── private ───────────────────────────────────────────────────────────────

    def _find_bundles(self) -> list[Path]:
        if not self._bundle_dir.exists():
            raise FileNotFoundError(f"Bundle directory not found: {self._bundle_dir}")
        return sorted(
            p for p in self._bundle_dir.glob("*.json")
            if not any(p.name.startswith(pfx) for pfx in self._SKIP_PREFIXES)
        )

    def _process_bundle(self, bundle: dict, summary: SyntheaIngestionSummary) -> None:
        entries = bundle.get("entry", [])

        # Build urn:uuid → resource_id map for intra-bundle reference resolution
        urn_map: dict[str, str] = {}
        for entry in entries:
            full_url = entry.get("fullUrl", "")
            rid = entry.get("resource", {}).get("id", "")
            if full_url and rid:
                urn_map[full_url] = rid

        # Partition entries by resource type (single pass)
        by_type: dict[str, list[dict]] = {}
        for entry in entries:
            resource = entry.get("resource", {})
            rtype = resource.get("resourceType", "")
            by_type.setdefault(rtype, []).append(resource)

        # Process in FK-dependency order
        patient_map = self._ingest_patients(by_type.get("Patient", []), summary)
        encounter_map = self._ingest_encounters(by_type.get("Encounter", []), patient_map, summary)
        self._ingest_observations(by_type.get("Observation", []), patient_map, encounter_map, summary)
        self._ingest_conditions(by_type.get("Condition", []), patient_map, encounter_map, summary)
        self._ingest_medications(by_type.get("MedicationRequest", []), patient_map, encounter_map, summary)
        self._db.commit()

    def _ingest_patients(
        self, resources: list[dict], summary: SyntheaIngestionSummary
    ) -> dict[str, str]:
        """Returns {fhir_id: db_uuid, urn:uuid:fhir_id: db_uuid}."""
        fhir_to_db: dict[str, str] = {}
        summary.patients.fetched += len(resources)
        for resource in resources:
            try:
                mapped = map_patient(resource)
                db_id = self._upsert(Patient, mapped, "fhir_id", summary.patients)
                if db_id:
                    rid = resource["id"]
                    db_id_str = str(db_id)
                    fhir_to_db[rid] = db_id_str
                    # Cover urn:uuid: reference format used by Synthea
                    fhir_to_db[f"urn:uuid:{rid}"] = db_id_str
            except Exception as exc:
                summary.patients.errors += 1
                summary.error_log.append(f"Patient {resource.get('id')}: {exc}")
                self._db.rollback()
        return fhir_to_db

    def _ingest_encounters(
        self,
        resources: list[dict],
        patient_map: dict[str, str],
        summary: SyntheaIngestionSummary,
    ) -> dict[str, str]:
        fhir_to_db: dict[str, str] = {}
        if not patient_map:
            return fhir_to_db
        summary.encounters.fetched += len(resources)
        for resource in resources:
            try:
                mapped = map_encounter(resource, patient_map)
                if mapped is None:
                    summary.encounters.skipped += 1
                    continue
                db_id = self._upsert(Encounter, mapped, "fhir_id", summary.encounters)
                if db_id:
                    rid = resource["id"]
                    db_id_str = str(db_id)
                    fhir_to_db[rid] = db_id_str
                    fhir_to_db[f"urn:uuid:{rid}"] = db_id_str
            except Exception as exc:
                summary.encounters.errors += 1
                summary.error_log.append(f"Encounter {resource.get('id')}: {exc}")
                self._db.rollback()
        return fhir_to_db

    def _ingest_observations(
        self,
        resources: list[dict],
        patient_map: dict[str, str],
        encounter_map: dict[str, str],
        summary: SyntheaIngestionSummary,
    ) -> None:
        summary.observations.fetched += len(resources)
        for resource in resources:
            try:
                mapped = map_observation(resource, patient_map, encounter_map)
                if mapped is None:
                    summary.observations.skipped += 1
                    continue
                self._upsert(Observation, mapped, "fhir_id", summary.observations)
            except Exception as exc:
                summary.observations.errors += 1
                summary.error_log.append(f"Observation {resource.get('id')}: {exc}")
                self._db.rollback()

    def _ingest_conditions(
        self,
        resources: list[dict],
        patient_map: dict[str, str],
        encounter_map: dict[str, str],
        summary: SyntheaIngestionSummary,
    ) -> None:
        summary.conditions.fetched += len(resources)
        for resource in resources:
            try:
                mapped = map_condition(resource, patient_map, encounter_map)
                if mapped is None:
                    summary.conditions.skipped += 1
                    continue
                self._upsert(Condition, mapped, "fhir_id", summary.conditions)
            except Exception as exc:
                summary.conditions.errors += 1
                summary.error_log.append(f"Condition {resource.get('id')}: {exc}")
                self._db.rollback()

    def _ingest_medications(
        self,
        resources: list[dict],
        patient_map: dict[str, str],
        encounter_map: dict[str, str],
        summary: SyntheaIngestionSummary,
    ) -> None:
        summary.medications.fetched += len(resources)
        for resource in resources:
            try:
                mapped = map_medication_request(resource, patient_map, encounter_map)
                if mapped is None:
                    summary.medications.skipped += 1
                    continue
                self._upsert(MedicationRequest, mapped, "fhir_id", summary.medications)
            except Exception as exc:
                summary.medications.errors += 1
                summary.error_log.append(f"MedicationRequest {resource.get('id')}: {exc}")
                self._db.rollback()

    def _upsert(self, model, row: dict, unique_field: str, res_summary: ResourceSummary) -> uuid.UUID | None:
        fhir_id = row.get(unique_field)
        existing = (
            self._db.query(model)
            .filter(getattr(model, unique_field) == fhir_id)
            .first()
        )
        if existing:
            res_summary.skipped += 1
            return existing.id
        obj = model(**row)
        self._db.add(obj)
        self._db.flush()
        res_summary.inserted += 1
        return obj.id
